<?php

declare(strict_types=1);

// @phpcs:disable Generic.Files.LineLength

namespace BeycanPress\TokenicoLite;

class Lang
{
    /**
     * Get language strings
     * @return array<string,string>
     */
    public static function get(): array
    {
        return [
            "waitingConnection" => esc_html__("Establishing connection please wait!", 'tokenico'),
            "connectionRefused" => esc_html__('Connection refused', 'tokenico'),
            "donateRejected" => esc_html__('Donate rejected', 'tokenico'),
            "cancel" => esc_html__('Cancel', 'tokenico'),
            "confirm" => esc_html__('Confirm', 'tokenico'),
            "deploy" => esc_html__('Deploy', 'tokenico'),
            "insufficientBalance" => esc_html__('You do not have the balance to cover the amount you will pay + transaction gas fees!', 'tokenico'),
            "unexpectedError" => esc_html__('An unexpected error has occurred', 'tokenico'),
            "pleaseWait" => esc_html__('Please wait...', 'tokenico'),
            "transactionId" => esc_html__('Transaction Id: ', 'tokenico'),
            'intrinsicGasTooLow' => esc_html__('Intrinsic gas too low', 'tokenico'),
            'fieldCannotBeEmpty' => esc_html__('"%s" field cannot be left blank.', 'tokenico'),
            'confirmNetwork' => esc_html__('You are about to publish the presale on network "%s". Do you want to continue?', 'tokenico'),
            'bigStartDate' => esc_html__('The start date cannot be greater than the end date.', 'tokenico'),
            'bigMinContribution' => esc_html__('The minimum contribution cannot be greater than the maximum contribution.', 'tokenico'),
            'bigMinMaxContribution' => esc_html__('Minimum contribution and maximum contribution cannot exceed the total sales limit!', 'tokenico'),
            'deployContract' => esc_html__('Contract being deployed please wait...', 'tokenico'),
            'saleApprove' => esc_html__('To be able to sell tokens, the contract address needs confirmation of use. Please confirm!', 'tokenico'),
            'invalidTokenAddress' => esc_html__('I think you entered an invalid token address. Please enter a valid token address.', 'tokenico'),
            'approveProcess' => esc_html__('Please wait for the approval process.', 'tokenico'),
            'connectionRejected' => esc_html__('Connection rejected!', 'tokenico'),
            'pleaseEnterAmount' => esc_html__('Please enter an amount!', 'tokenico'),
            "purchaseFailed"  => esc_html__("An error occurred during the purchase!", 'tokenico'),
            "claim"  => esc_html__("Claim", 'tokenico'),
            "requestRejected" => esc_html__("Request rejected!", 'tokenico'),
            "claimSuccessful" => esc_html__("The claim operation completed successfully. The tokens you purchased will be reflected in your account shortly.", "tokenico"),
            "walletNotDetected" => esc_html__("The {wallet} wallet you want to connect to could not be detected!", "tokenico"),
            'successCopy' => esc_html__('Copying to clipboard was successful!', 'tokenico'),
            'saleBalanceError' => esc_html__('There is not enough balance in your wallet for the token you want to sell!', 'tokenico'),
            'insufficientLiquidity' => esc_html__('Insufficient liquidity by the seller.', 'tokenico'),
            'claimConfirm' => esc_html__('A total of {token} tokens that you have purchased will be sent to your address.', 'tokenico'),
            'getDatesError' => esc_html__('There was a problem setting the dates, please refresh the page and try again.', 'tokenico'),
            'alreadyProcessing' => esc_html__("A connection request is already pending, check the wallet plugin!", 'tokenico'),
            'paymentAmount' => esc_html__('The payment amount cannot be less than zero.', 'tokenico'),
            "youDidintPay" => esc_html__("You did not pay the publish fee!", 'tokenico'),
            'presalePublish' => esc_html__('Please confirm the Presale publish process!', 'tokenico'),
            'minContribution' => esc_html__('Minimum amount you can purchase: {min} {tokenSymbol}', 'tokenico'),
            'maxContribution' => esc_html__('Maximum amount you can purchase: {max} {tokenSymbol}', 'tokenico'),
            'presaleEnded' => esc_html__('Presale ended!', 'tokenico'),
            'presaleNotStarted' => esc_html__('Presale not started!', 'tokenico'),
            'presaleEnded2' => esc_html__('The presale is over as the total sales limit has been reached!', 'tokenico'),
            'exceedingRemainingLimit' => esc_html__('You are exceeding the remaining total purchase limit!', 'tokenico'),
            'yourRemainingLimitDone' => esc_html__('You have reached the maximum purchase limit', 'tokenico'),
            'yourRemainingLimitExceeding' => esc_html__('You are exceeding your remaining participation limit!', 'tokenico'),
            "yourRemainingLimitExceeding2" => esc_html__('You are exceeding your remaining contribution limit! Your remaining contribution limit {limit}!', 'tokenico'),
            'maxContributionExceeding' => esc_html__('You are exceeding the maximum purchase limit!', 'tokenico'),
            'minContributionExceeding' => esc_html__('You are exceeding the minimum purchase limit!', 'tokenico'),
            'disabledInstantTransfer' => esc_html__('The method is disabled because instant transfer is on!', 'tokenico'),
            'presaleNotEnded' => esc_html__('This method is not active because the presale is not over!', 'tokenico'),
            'youDidNotBuyToken' => esc_html__('You have never purchased any tokens!', 'tokenico'),
            'yourTokensAlreadySent' => esc_html__('Your purchased tokens have already been sent!', 'tokenico'),
            'purchaseProcess' => esc_html__('Please wait for your purchase to be confirmed...', 'tokenico'),
            'claimProcess' => esc_html__('Please wait for your purchase to be confirmed...', 'tokenico'),
            'purchaseProcessSuccess' => esc_html__('Your purchase has been confirmed successfully and the tokens have been transferred and they will be reflected in your wallet shortly.', 'tokenico'),
            'purchaseProcessSuccess2' => esc_html__('Your purchase has been confirmed successfully. To transfer your tokens to your wallet, please wait for the presale to end and transfer your tokens to your wallet using the "claim" button that will be activated.', 'tokenico'),
            'confirmPurchaseProcess' => esc_html__('Please confirm the purchase from your wallet!', 'tokenico'),
            "confirmClaimProcess" => esc_html__('Please confirm the claim process from your wallet!', 'tokenico'),
            "contractDeployMsg" => esc_html__('Please confirm contract deploy request!', 'tokenico'),
            "notDeployedInThisNetwork" => esc_html__('A contract has not been deployed on this network before, so you need to deploy the contract before you can continue publishing presales!', 'tokenico'),
            "presalePublished" => esc_html__('The presale has been released successfully.', 'tokenico'),
            "deployError" => esc_html__('An error occurred while deploying the presale contract!', 'tokenico'),
            "approveError" => esc_html__('An error occurred while approving the presale contract!', 'tokenico'),
            "publishError" => esc_html__('An error occurred while publishing the presale!', 'tokenico'),
            "balanceError" => esc_html__('Each network has a set presale publishing commission fee, which you do not cover. Commission fees are indicated at the top.', 'tokenico'),
            "gasError" => esc_html__('There was a problem getting estimate gas!', 'tokenico'),
            "waitingForTimeCreation" => esc_html__('Please wait for the timestamps to be generated!', 'tokenico'),
            "youHaveAlreadyCreated" => esc_html__('You have already created a presale with this ID!', 'tokenico'),
            "publishProcess" => esc_html__('Please wait for the publish process!', 'tokenico'),
            "startDateLessFromNow" => esc_html__('The start date cannot be less than the current date!', 'tokenico'),
            "invalidNumberOfParameters" => esc_html__('Invalid number of parameters!', 'tokenico'),
            "noFoundAnySale" => esc_html__('No purchases were found for this presale!', 'tokenico'),
            "noFoundAnyPresale" => esc_html__('No relevant presale found!', 'tokenico'),
            "youDidNotSendAnyFund" => esc_html__('You did not send any funds!', 'tokenico'),
            "presaleStatusChanged" => esc_html__('Presale status has changed. The page will be refreshed!', 'tokenico'),
            "youAreTheReceiver" => esc_html__('You cannot participate in your own presale!', 'tokenico'),
            "lessMinContributionAmount" => esc_html__('The exchange rate should not be less than 1 when calculated based on the minimum participation amount. Please increase your exchange rate.', 'tokenico'),
            "presaleJustStarted" => esc_html__('Looks like presales have just started or finished. Please wait a while, refresh the page and try again!', 'tokenico'),
            "noAbiFound" => esc_html__('No abi found!', 'tokenico'),
            "noBytecodeFound" => esc_html__('No bytecode found!', 'tokenico'),
            "redirecting" => esc_html__('Redirecting...', 'tokenico'),
            "wcProjectIdError" => esc_html__('The purchase process will not work because you have not entered the WalletConnect Project ID. Please obtain a WalletConnect Project ID and add it to the relevant field in the settings.', 'tokenico'),
            "detected" => esc_html__('Detected', 'tokenico'),
            "download" => esc_html__('Download', 'tokenico'),
            "onlyDesktop" => esc_html__('Only available on desktop', 'tokenico'),
            "openInApp" => esc_html__('Open in app', 'tokenico'),
            "openInAppManual" => esc_html__('Open in app manually', 'tokenico'),
            "notDelegated" => esc_html__('Owner token account is not delegated to the presale account!', 'tokenico'),
            "pleaseAcceptReloadPage" => esc_html__('Please accept the request to reload the page!', 'tokenico'),
            "lockedWallet" => esc_html__('Your wallet is locked! Please open first and try connect again.', 'tokenico'),
            "notAcceptedChain" => esc_html__('The chain you are trying to connect to is not accepted! Please choose right one and try connect again!', 'tokenico'),
            "transactionReverted" => esc_html__('Transaction reverted! You can see reason on the TronScan with click link below.', 'tokenico'),
            "pleaseEnterRpc" => esc_html__('Please enter an RPC address in the settings!', 'tokenico'),
            "solanaInfo" => esc_html__('If you don\'t see “Approve” on the Phantom screen and you just created your token, please transfer it to another wallet and try to create a presale again!'),
            "openInAppMsg" => esc_html__('This is a informational message. You tried to redirect to the application with Deep Link. If no application guidance has been made. It means you do not have the relevant wallet application. Please get the relevant wallet app from the app market.', 'tokenico'),
            "openInAppManualMsg" => esc_html__('This is an informational message. This wallet does not support Deep Linking. Therefore, you can try to connect to this wallet directly using the browser in the application.', 'tokenico'),
            "onlyDesktopMsg" => esc_html__('This is an informational message. This wallet does not have support on mobile platforms. So please try connecting to the wallet via a desktop browser.', 'tokenico'),
            "downloadManualMsg" => esc_html__('This is an informational message. No download link is provided for this wallet. So please try connecting after downloading the wallet.', 'tokenico'),
            "downloadMsg" => esc_html__('This is an informational message. You were redirected to the download link because the relevant wallet could not be detected in your browser. Please try connecting again after installing the wallet.', 'tokenico'),
        ];
    }
}
